name: Update Version and Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Important: this ensures all tags and branches are fetched
      
      - name: Update version in manifest
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ github.ref_name }}\"/" custom_components/terneo/manifest.json
      
      - name: Commit and push manifest changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add custom_components/terneo/manifest.json
          git commit -m "Update version in manifest to ${{ github.ref_name }}"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ishikht/ha-terneo-integration.git
          git push

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
